### ISSUE TITLE
Safari 12 compatibility

### ISSUE THREAD

**Issue by mstislavm** [dominique-mueller/angular-notifier#116]
Hello,

angular-notifier (v.4.1.1)  doesn’t work with Safari 12 (14606.1.36.1.9).
Error:

> 
Error: Uncaught (in promise): TypeError: _this.element.animate is not a function. (In '_this.element.animate(animationData.keyframes, animationData.options)', '_this.element.animate' is undefined) 

Steps to reproduce the issue:
1. Run browser
2. open angular-notifier demo: https://stackblitz.com/edit/angular-notifier-demo
3. click any Show notifications button in demo
![2018-12-06 14 55 59](https://user-images.githubusercontent.com/8149689/49582760-168bab80-f967-11e8-8227-07a5e8ce34f1.png)

**Comment by gethinoakes** [comment]
Just encountered this issue myself, I guess we both failed to correctly read the README file!

[README: Browser support & polyfills](https://github.com/dominique-mueller/angular-notifier/blob/develop/README.md#browser-support--polyfills)

For Safari you need to include the [web-animations-js](https://github.com/web-animations/web-animations-js) polypill. 

We have just done this in our Angular project and it fixed the issue.

**Comment by mstislavm** [comment]
solved by adding web-animations-js polyfill
